# Generated by Django 4.1.4 on 2022-12-27 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms', '0002_book_book_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date_of_book',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='identifier',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
