# Generated by Django 4.1.4 on 2022-12-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='storage_limit',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
    ]
